version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fkdfgknfnkngsnlneiq9348fjef
      POSTGRES_DB: mangoauth
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  mangoauth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mangoauth-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mangoauth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: fkdfgknfnkngsnlneiq9348fjef
      FLYWAY_URL: jdbc:postgresql://postgres:5432/mangoauth
      FLYWAY_USER: root
      FLYWAY_PASSWORD: fkdfgknfnkngsnlneiq9348fjef
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
