spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:postgresql://localhost:5432/mangoauth
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

app:
  mail:
    username: dendeberiaoleksandr@gmail.com
    password: wzkl mmqc yres yegu

flyway:
  url: jdbc:postgresql://localhost:5432/mangoauth
  schemas: public
  user: postgres
  password: postgres
